[program:act_eval_server_turning_radio_diag]
command=/opt/supervisor-scripts/act-eval-server-turning-radio-diag.sh
directory=/workspace/behavior-2026/lp-act-v1
autostart=false
autorestart=unexpected
startsecs=1
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/portal/act_eval_server_turning_radio_diag.log
stderr_logfile=/var/log/portal/act_eval_server_turning_radio_diag.log
redirect_stderr=true
stdout_logfile_maxbytes=0
environment=HOME="/root",USER="root"
