[program:act_eval_turning_radio_instance0_full]
command=/opt/supervisor-scripts/act-eval-instance0-full.sh
directory=/workspace/behavior-2026/BEHAVIOR-1K
autostart=false
autorestart=false
startsecs=1
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/portal/act_eval_turning_radio_instance0_full.log
stderr_logfile=/var/log/portal/act_eval_turning_radio_instance0_full.log
redirect_stderr=true
stdout_logfile_maxbytes=0
environment=HOME="/root",USER="root"
