[program:lpact_eval_server_gpu1]
command=/opt/supervisor-scripts/lpact-eval-server-gpu1.sh
directory=/workspace/behavior-2026/lp-act-v1
autostart=false
autorestart=unexpected
startsecs=1
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/portal/lpact_eval_server_gpu1.log
stderr_logfile=/var/log/portal/lpact_eval_server_gpu1.log
redirect_stderr=true
stdout_logfile_maxbytes=0
environment=HOME="/root",USER="root"
