[program:lpact_eval_turning_radio_public_0_4]
command=/opt/supervisor-scripts/lpact-eval-public-0-4.sh
directory=/workspace/behavior-2026/BEHAVIOR-1K
autostart=false
autorestart=false
startsecs=1
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/portal/lpact_eval_turning_radio_public_0_4.log
stderr_logfile=/var/log/portal/lpact_eval_turning_radio_public_0_4.log
redirect_stderr=true
stdout_logfile_maxbytes=0
environment=HOME="/root",USER="root"
