[program:robocasa_lpact_tiny_gpu1_v1]
command=/opt/supervisor-scripts/robocasa-lpact-tiny-gpu1-v1.sh
directory=/workspace/lp-act-v1/robocasa-lp-act-v1
autostart=false
autorestart=false
startsecs=0
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/portal/robocasa_lpact_tiny_gpu1_v1.log
stderr_logfile=/var/log/portal/robocasa_lpact_tiny_gpu1_v1.log
redirect_stderr=true
stdout_logfile_maxbytes=0
environment=HOME="/root",USER="root"
