[program:robocasa_act_full_gpu0_v2]
command=/opt/supervisor-scripts/robocasa-act-full-gpu0-v2.sh
directory=/workspace/lp-act-v1/robocasa-lp-act-v1
autostart=false
autorestart=unexpected
startsecs=1
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/portal/robocasa_act_full_gpu0_v2.log
stderr_logfile=/var/log/portal/robocasa_act_full_gpu0_v2.log
redirect_stderr=true
stdout_logfile_maxbytes=0
environment=HOME="/root",USER="root"
